### ISSUE TITLE
Seems like on unix, 'not win32' will always be true, therefore `unix` is redundant?

### ISSUE THREAD

**Issue by hughperkins** [torch/paths#14]
Seems like on unix, 'not win32' will always be true, therefore `unix` is redundant?

https://github.com/torch/paths/blob/master/CMakeLists.txt#L11

```
IF (UNIX OR NOT WIN32)
```

**Comment by soumith** [comment]
maybe he was working around a cmake bug. paths is quite old, before CMake was actually mature like it is today. if an incoming PR cleans it up, will accept.
